### ISSUE TITLE
Qulice configuration - no license specified.

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-ssh#15]
1. Checkout master branch
2. run `mvn qulice:check -Pqulice`
3. There are multiple `Line does not match expected header line of ' * BSD License'. (HeaderCheck)` messages.

This is a known bug of qulice configuration in parent-0.31 (jcabi/jcabi-parent#19), accessed via jcabi-0.16. Suggested action is waiting until jcabi/jcabi#297 fix is released and upgrading jcabi version.

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please

**Comment by yegor256** [comment]
@maurezen fixed in a5bf49c thanks
