### ISSUE TITLE
Build failed on windows with lots of EOL violations

### ISSUE THREAD

**Issue by YamStranger** [jcabi/jcabi-ssh#23]
@dmarkov Looks like we need to add .gitattributes to force EOL of the repo.

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by YamStranger** [comment]
@yegor256. It is known problem, qulice fail if default system EOF not like in linux. So we need add .attributes to repository for force setting Unix-like end of line to git repository. 
AppVeyor use linux like EOF. 
This repository will not build successfully if you install git, install maven, clone repo and just build. 
Here is some examples of same problem at different repositories:
This is issue same as here https://github.com/jcabi/jcabi-maven-skin/issues/24 (build failed on Windows)
same is here https://github.com/yegor256/takes/issues/148
fix mast be like here https://github.com/jcabi/jcabi-aether/pull/59/files#diff-fc723d30b02a4cca7a534518111c1a66 or like here https://github.com/jcabi/jcabi-dynamo/pull/43

**Comment by yegor256** [comment]
@YamStranger fixed in https://github.com/jcabi/jcabi-ssh/commit/fd9c9ca01eb82db6d49fe7e58365a02f25ee00c3
