### ISSUE TITLE
SSH.java:70-72: This class has common data,...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-ssh#27]
Puzzle `21-74327cdd` in `src/main/java/com/jcabi/ssh/SSH.java:70-72` has to be resolved: This class has common data, implementation of exec() and constructor validations with SSHByPassword class. Common functionality should be extracted into a separate module.... The puzzle was created by Suseika on 22-Jun-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@kpbird This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here; Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by kpbird** [comment]
@dmarkov issue fixed please check pull request

**Comment by dmarkov** [comment]
> @dmarkov issue fixed please check pull request

@kpbird OK, thanks, will take a look soon

**Comment by dmarkov** [comment]
@kpbird check this ["no obligations principle"](http://www.xdsd.org/2014/04/13/no-obligations-principle.html).. This task is on your name for at least 17 days. If you can't close it within the next 48 hours I will have to assign someone else to it. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck. do not forget that you should remove the `@todo` puzzle from the source code. -30 to your rating, your total score is [-60](http://www.netbout.com/b/35593?open=rating)

**Comment by dmarkov** [comment]
@kpbird it takes too long. Usually, we expect any task to be finished in less than a week. I'll assign someone else. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle

added -60 to your rating, now it is equal to [-180](http://www.netbout.com/b/35593?open=rating)

**Comment by dmarkov** [comment]
@olegsimanov the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here... Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by olegsimanov** [comment]
Honestly I don't understand this task really. 
Should I review changes made by @kpbird in this commit https://github.com/kpbird/jcabi-ssh/commit/2f5c0736069e27409d682eabf10a3129ecb4a966 or should I perform my own refactoring?

**Comment by dmarkov** [comment]
@olegsimanov the ticket is with you for 15 days already. If it is not finished in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle, [this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck; do not forget to remove the TODO puzzle from the source code; -30 added to your rating, current score is: [-60](http://www.netbout.com/b/35927?open=rating)

**Comment by dmarkov** [comment]
@olegsimanov it takes too long. Usually, we expect any task to be finished in less than a week. I'll assign someone else. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle... -60 added to your rating, at the moment it is: [-120](http://www.netbout.com/b/35927?open=rating)

**Comment by jrdalpra** [comment]
@dmarkov it's issue is assigned to me at netbout. Should I work on it?

**Comment by dmarkov** [comment]
@jrdalpra This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here. Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by jrdalpra** [comment]
@dmarkov ok. doing.

**Comment by jrdalpra** [comment]
@dmarkov PR https://github.com/jcabi/jcabi-ssh/pull/39 is waiting for someone to review. Thanks.

**Comment by dmarkov** [comment]
> @dmarkov PR https://github.com/jcabi/jcabi-ssh/pull/39 is waiting for someone to review. Thanks.

@jrdalpra np :)

**Comment by jrdalpra** [comment]
@dmarkov PR was merged. Can you close the issue? Thanks.

**Comment by jrdalpra** [comment]
@dmarkov can you close? :) thanks

**Comment by dmarkov** [comment]
> @dmarkov PR was merged. Can you close the issue? Thanks.

@jrdalpra sure, will do right after the next deployment cycle

**Comment by dmarkov** [comment]
@yegor256 Closing this issue now...

**Comment by dmarkov** [comment]
@jrdalpra Thanks for your contribution, **30 mins** was added to your account, payment ID is `AP-1GS90901FW705825D`, 285 hours and 35 mins spent total... +30 to your rating, your total score is [+128](http://www.netbout.com/b/36044?open=rating)

**Comment by jrdalpra** [comment]
@dmarkov thanks

**Comment by dmarkov** [comment]
> @dmarkov thanks

@jrdalpra np :)
