### ISSUE TITLE
SSHByPasswordTest.java:63-65: SSH server setup in this...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-ssh#28]
Puzzle `21-5047b140` in `src/test/java/com/jcabi/ssh/SSHByPasswordTest.java:63-65` has to be resolved: SSH server setup in this class is nearly identical to the one in {@link SSHTest}. It should be extracted in a separate reusable module.... The puzzle was created by Suseika on 22-Jun-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@prondzyn please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here... The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by prondzyn** [comment]
@dmarkov PR prepared

**Comment by dmarkov** [comment]
> @dmarkov PR prepared

@prondzyn OK thanks. in the future, would be great to mention the name of the pull request, for traceability

**Comment by prondzyn** [comment]
@dmarkov will remember :)

**Comment by prondzyn** [comment]
@dmarkov changes merged

**Comment by dmarkov** [comment]
> @dmarkov will remember :)

@prondzyn thanks :)

**Comment by dmarkov** [comment]
@yegor256 Thanks all, I am closing

**Comment by dmarkov** [comment]
@prondzyn paid, thanks, added **30 mins** to your account, payment `AP-0H11150236122211C`, 194 hours and 38 mins was spent... +30 added to your rating, current score is: [+60](http://www.netbout.com/b/35715?open=rating)
