### ISSUE TITLE
SSHTest.java:164-167: EchoCommand and EchoCommandCreator are duplicated...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-ssh#29]
Puzzle `21-40f93421` in `src/test/java/com/jcabi/ssh/SSHTest.java:164-167` has to be resolved: EchoCommand and EchoCommandCreator are duplicated in SSHTest and SSHByPasswordTest, these duplicates should be extracted into package com.jcabi.ssh.mock under src/main/java, renamed to MkCommandCreator/MkCommand and unit-tested.... The puzzle was created by Suseika on 22-Jun-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@nikoladespotoski can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here. The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dmarkov** [comment]
@nikoladespotoski this task is in your hands for 15 days already... do not forget to remove the TODO puzzle from the source code... -30 to your rating, your total score is [+340](http://www.netbout.com/b/36438?open=rating)

**Comment by NikolaDespotoski** [comment]
@dmarkov assign someone else

**Comment by dmarkov** [comment]
> @dmarkov assign someone else

@nikoladespotoski someone else will help in this task, no problem at all

**Comment by dmarkov** [comment]
@amihaiemil the task is yours please proceed

**Comment by amihaiemil** [comment]
@dmarkov  I created PR #43 for this issue.

**Comment by dmarkov** [comment]
> @dmarkov  I created PR #43 for this issue.

@amihaiemil thanks

**Comment by amihaiemil** [comment]
@dmarkov The PR #43 for this issue was successfully merged and closed. Please close this ticket. Thanks.

**Comment by amihaiemil** [comment]
@dmarkov The PR #43 has also been deployed successfully. Please close this ticket. Thanks.

**Comment by dmarkov** [comment]
@yegor256 Thanks, closed

**Comment by dmarkov** [comment]
@amihaiemil **30 mins** added to your account (payment number `AP-06N78733HJ4287945`), many thanks for your contribution! 309 hours and 25 mins spent here.. +30 added to your rating, at the moment it is: [+15](http://www.netbout.com/b/36402?open=rating)
