### ISSUE TITLE
Looks like common data is already extracted

### ISSUE THREAD

**Issue by olegsimanov** [jcabi/jcabi-ssh#35]
It looks like common data is already extracted by @kpbird here: https://github.com/kpbird/jcabi-ssh/commit/2f5c0736069e27409d682eabf10a3129ecb4a966
Should I perform my own refactoring anyway?

**Comment by dmarkov** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@olegsimanov I don't understand this ticket at all... what is the problem? see this: http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html
