### ISSUE TITLE
Does jcabi-ssh support vi command?

### ISSUE THREAD

**Issue by wcc526** [jcabi/jcabi-ssh#45]
Does jcabi-ssh support vi command?

Can I input h+i+j+k by use jcabi-ssh?

**Comment by dmarkov** [comment]
@yegor256 take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@wcc526 jcabi-ssh will just send whatever you provide to the SSH tunnel. this can be vi commands too. anything that you can send via a tunnel.
