### ISSUE TITLE
Rredirect output to null or file

### ISSUE THREAD

**Issue by plui31** [jcabi/jcabi-ssh#51]
I'm writing a small application to connect to a list of servers through SSH and execute a few commands. I'm using jcabi-ssh. When I run the program, jcabi-ssh outputs to the console with lines such as:

```
[main] WARN com.jcabi.ssh.SSH - Permanently added '192.168.4.2' (RSA) to the list of known hosts.
[main] INFO com.jcabi.ssh.Execution$Default - $ ping -c 1 google.com
```
My code snippet is as follows:

```
Shell shell = new SSHByPassword(targetServer.toString(), Integer.parseInt(port), username.toString(), password.toString());
exitCode=shell.exec("ping -c 1 google.com",stdin,stdout,stderr);
```

I would like to either hide the console output or redirect it to a file. I looked through the source but it seems like I can't do it through the method call. Is there a way to do what I wanted?

Thanks!

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@plui31 you should configure your logging facility. jcabi-ssh logs all that through slf4j, which sends log lines later to log4j (or something else). just look at your log4j configuration and suppress that loggers.
