### ISSUE TITLE
sudo command without password required

### ISSUE THREAD

**Issue by vbledar** [jcabi/jcabi-ssh#53]
Hi,

Is it possible to send a sudo command without password required? What I mean is that I can execute a command to change the user, for example:

sudo /bin/change_user.sh

change_user.sh should change the user as if you executed su - username.

This command doesn't require the sudoer's password to be entered. When I send this command through the java client I get an empty response and later when I execute another command I get a permission denied which is correct because running whoami I can see that the user has not changed.

Any help is much appreciated.

Thanks.

**Comment by dmarkov** [comment]
@yegor256 take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@vbledar this library doesn't control what happens _on the server_. All it does is connecting you with the server and sending commands there, either `sudo` or anything else. You manage permissions on the server, not on the client. Make sense?
