### ISSUE TITLE
How to interact with many commands

### ISSUE THREAD

**Issue by fdabrao** [jcabi/jcabi-ssh#58]
Is there any way to interact with shell? Like 
```
ssh.exec("export TEST=1");
ssh.exec("echo $TEST"); // will print 1
```
how to do this?

Regards

**Comment by dmarkov** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@fdabrao there is no way to do that. All environment variables live only within one session. Thus, the best you can do is:

```
ssh.exec("TEST=1 echo $TEST");
```

**Comment by fdabrao** [comment]
Hello,

I did it with Expect using session and channel and it worked.

Regards,
