### ISSUE TITLE
[Question] SFTP upload of sh script and running

### ISSUE THREAD

**Issue by ioreskovic** [jcabi/jcabi-ssh#59]
I have a relatively simple use case.
  
I receive an InputStream of a script on my local machine, together with the destination on the remote machine. I need to do an SFTP upload to destination, chmod it and run it via "/bin/bash".
  
Now, given the following API  
`void transferAndRun(InputStream scriptInputStream, String destinationLocation) {
    ...
}`

I don't seem to be able to find a way to upload it, because the most verbose API I found is this:
`shellProvider.shell().exec(command, scriptInputStream, Logger.stream(Level.INFO, this), Logger.stream(Level.WARNING, this))`

Where will the contents of the InputStream be uploaded? Under which name? Is there something I'm overlooking?

**Comment by dmarkov** [comment]
@yegor256 please dispatch this issue

**Comment by yegor256** [comment]
@ioreskovic take a look at how we upload files, here: https://github.com/yegor256/rultor/blob/1.62.2/src/main/java/com/rultor/agents/daemons/StartsDaemon.java#L170-L205

**Comment by ioreskovic** [comment]
So, to sum up, I need to do the following:

1. Try to cd to desired dir
1. a. Create it if it doesnt exist
2. Cat the contents of the input stream into a file with desired name
3. Chmod it
4. Run it

Thank you!
