### ISSUE TITLE
shell.exec() closing System.out

### ISSUE THREAD

**Issue by lubars** [jcabi/jcabi-ssh#63]
I'm opening an interactive session (in this case using bash) as follows:

```
import com.jcabi.ssh.Shell;

System.out.println("(Before)");  // gets printed
Shell shell = new com.jcabi.ssh.SSH(addr, port, user, key);
int exitValue = shell.exec("bash", System.in, System.out, System.err);
System.out.println("(After)"); // doesn't get printed
```
After the bash session is closed (via the user typing `exit`), no further output is seen until the application exits:

```
local$ ./test-jcabi
(Before)
remote# pwd
/home/centos
remote# exit
local$
```

I created a FilterOutputStream to see if System.out was being closed by shell.exec(), and if so whether I could circumvent it:: 

```
class UnclosableOutputStream extends FilterOutputStream {
    public UnclosableOutputStream(OutputStream out) {
        super(out);
    }
    public void close() throws IOException {
        System.out.println("Skipping close");
    }
}

UnclosableOutputStream myOutStream = new UnclosableOutputStream(System.out);
int exitValue = shell.exec("bash", System.in, myOutStream, System.err);

```

It prints the "Skipping close" message, so we know attempt is indeed being made to close System.out (and I believe succeeding despite the above code, because writing to System.out is still not working with this change).  Any ideas or help would be appreciated.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@lubars this is what is happening. We're calling `setOutputStream()` 
[here](https://github.com/jcabi/jcabi-ssh/blob/1.5.2/src/main/java/com/jcabi/ssh/Execution.java#L119). We provide `false` as a second parameter, which means that the stream should indeed be closed after usage: https://epaul.github.io/jsch-documentation/javadoc/com/jcraft/jsch/Channel.html#setOutputStream-java.io.OutputStream-boolean-

This is the default behavior we have now. It seems that you already found a solution with that `UnclosableOutputStream`. Do you think we should modify our library somehow instead?

**Comment by lubars** [comment]
Hi @yegor256 , thanks for your reply.  For reasons I don't understand, the `UncloseableOutputStream` workaround doesn't seem to work (even though the "Skipping close" gets printed).  Any ideas?

**Comment by lubars** [comment]
Hi @yegor256 , thanks for your reply.  The reason I posted was because the `UncloseableOutputStream` technique wasn't working for me, but now that I'm using it for all three streams things are working well:

```
	class UnclosableOutputStream extends FilterOutputStream {
	    public UnclosableOutputStream(OutputStream out) {
	        super(out);
	    }
	    public void close() throws IOException {
	    	out.flush();
	    }
	}

	class UnclosableInputStream extends FilterInputStream {
	    protected UnclosableInputStream(InputStream in) {
			super(in);
	    }
	    public void close() throws IOException {
	    	in.reset();
	    }
	}

		UnclosableOutputStream outStream = new UnclosableOutputStream(System.out);
		UnclosableOutputStream errStream = new UnclosableOutputStream(System.err);
		UnclosableInputStream inStream = new UnclosableInputStream(System.in);
		int exitValue = shell.exec(command, inStream, outStream, errStream);
```

Since this technique works, I don't think the library needs to be modified; if you were to make a change, I'd suggest modifying the library to set `dontClose` to `true` when it detects that the output stream is one of System.out, System.err, or System.in; in what I imagine is the extremely rare case  somebody wanted those streams closed, they could do so themselves after `exec()` returns.

**Comment by 0crat** [comment]
Oops! Job `gh:jcabi/jcabi-ssh#63` was not in scope
