### ISSUE TITLE
fake shell

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-ssh#65]
Let's create a fake shell for testing purposes.

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-ssh#65` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+2910](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `1.6`

**Comment by yegor256** [comment]
@rultor release, tag is `1.6`

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-ssh#65` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+3000](http://www.0crat.com/u/yegor256).
