### ISSUE TITLE
Is the library support use byte stream to receive response?

### ISSUE THREAD

**Issue by LoranceChen** [jcabi/jcabi-ssh#66]
Hi, my work consider command which maybe a long time task.So, I want display the process before it complete. That means get response stream to a callback rather a String type.  

I want ensure is the library support the feature?Thanks

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@LoranceChen yes, of course, you can do that. Just provide your own `InputStream` to us and keep reading from it.

**Comment by LoranceChen** [comment]
got it ;-)

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:jcabi/jcabi-ssh#66`.

**Comment by 0crat** [comment]
Oops! Job `gh:jcabi/jcabi-ssh#66` is not in scope.
