### ISSUE TITLE
Could use jcabi-ssh to scp files?

### ISSUE THREAD

**Issue by zhaozhiming** [jcabi/jcabi-ssh#7]
Could use jcabi-ssh to scp files? if yes, please give some example code, thank you.

**Comment by davidhtien** [comment]
Could this example be explained in more detail? I don't really see what's going here. Also I want to scp a byte array that is currently stored in memory would that be possible?

**Comment by devent** [comment]
A little bit old, but here is the explanation.

cat > %s command will read input from stdin and save it in the file %s (that will be replaced by the real file name, stored in file_name). The stdin is streamed in from the created FileInputStream(file).

**Comment by lubars** [comment]
Also effective:

`String.format("tee %s", SSH.escape(file_name))`

This has the advantage that you can prepend `sudo` if desired.
