### ISSUE TITLE
Session timeout is hard coded to 10s

### ISSUE THREAD

**Issue by orenbigel** [jcabi/jcabi-ssh#70]
SSH connection might take more that 10 seconds to connect.
The SSH class has 10s TO hard coded:
session.setServerAliveInterval(
    (int) TimeUnit.SECONDS.toMillis(Tv.TEN)

Could there be another SSH constructor that has an argument for the session TO ?

e.g.
public SSH(final String adr, final String user, final String priv, final sessionTO)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@orenbigel I set it to one second and 1mil seconds total
