### ISSUE TITLE
what is example.com? I didn't get it.

### ISSUE THREAD

**Issue by alihamza001** [jcabi/jcabi-ssh#71]
explain what should i use in place of example.com?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@alihamza001[/z](https://www.0crat.com/u/alihamza001) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C9V6HBZQS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@alihamza001 you should use the address of your server. If you are connecting to the local machine, use `localhost`.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
