### ISSUE TITLE
security is broken when temporary private key file won't get deleted if exception thrown

### ISSUE THREAD

**Issue by jimengliu** [jcabi/jcabi-ssh#73]
After using jcabi-ssh for a while, I noticed a lot of private key files inside /tmp folder. This poses significant security issues.

The problem is in session() function (in file src/main/java/com/jcabi/ssh/Ssh.java). The temporary private key file was constructed first, but it won't get deleted when there is exception thrown. Because the line to delete the file 

Files.deleteIfExists(file.toPath());

is within try{} block, not in finally{} block.

**Comment by yegor256** [comment]
@rultor release, tag is `1.6.1`

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-ssh#73` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by jimengliu** [comment]
@yegor256 Oh, I do see here http://central.maven.org/maven2/com/jcabi/jcabi-ssh/1.6.1/, but no link from https://mvnrepository.com. So, I am OK now. Thanks!
