### ISSUE TITLE
Is Jcabi-ssh compatible with Jersey?

### ISSUE THREAD

**Issue by aneevreddy** [jcabi/jcabi-ssh#74]
Hi,

I am work on Java rest services [Jersey]. Is Jcabi-ssh compatible with it. I tried to work on it, i am facing the below issue "org.glassfish.jersey.server.ContainerException: Java.lang.NoClassDefFoundError: com/jcabi/ssh/Shell"

Can you help me on this.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@aneevreddy[/z](https://www.0crat.com/u/aneevreddy) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C9V6HBZQS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@aneevreddy it is compatible, but you have to include the dependency (JAR) correctly.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-ssh#74` is not assigned, can't get performer

**Comment by aneevreddy** [comment]
@yegor256 can you please provide the dependency JAR files.

**Comment by yegor256** [comment]
@aneevreddy here: http://search.maven.org/#artifactdetails%7Ccom.jcabi%7Cjcabi-ssh%7C1.6.1%7C

**Comment by aneevreddy** [comment]
@yegor256 
I am very new to Java. I developed rest api application by using Java Jersey. For using SSH, I converted my Jersey project to Maven. Now it is showing Build Success, i build with Maven build. Now I run the application, when i accessing from postman, it throwing below error. please help me on this.

![error](https://user-images.githubusercontent.com/22213702/42087302-5d111ebe-7bb3-11e8-8da9-e4c65fa200b5.png)
![pom xml](https://user-images.githubusercontent.com/22213702/42087303-5d455760-7bb3-11e8-92fa-3cd23151715e.png)
![project structure](https://user-images.githubusercontent.com/22213702/42087305-5d78b876-7bb3-11e8-84b6-0b2732edb8cf.png)
![uservalidation method](https://user-images.githubusercontent.com/22213702/42087306-5dac3c32-7bb3-11e8-92cd-4f3576afe2a2.png)
