### ISSUE TITLE
Cannot connect to VM with RSA key as String

### ISSUE THREAD

**Issue by andrey-ryoo** [jcabi/jcabi-ssh#77]
Cannot connect to VM with RSA key because private key should have 600 permissions

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@andrey-ryoo[/z](https://www.0crat.com/u/andrey-ryoo) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C9V6HBZQS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by andrey-ryoo** [comment]
Pull request sent

**Comment by yegor256** [comment]
@andrey-ryoo This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-ssh#77` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
