### ISSUE TITLE
Turn off logging ??

### ISSUE THREAD

**Issue by ankit9289** [jcabi/jcabi-ssh#80]
How can we turn off logs that are being generated from jcabi

**Comment by 0crat** [comment]
@ankit9289[/z](https://www.0crat.com/u/ankit9289) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C9V6HBZQS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@ankit9289 they are going through SLF4j logging. You configure SLF4j the way you want and that's it.

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-ssh#80` is not assigned, can't get performer
