### ISSUE TITLE
class SSH.session create too many temp file

### ISSUE THREAD

**Issue by HuWeining** [jcabi/jcabi-ssh#83]
Make sure the title of the issue explains the problem you are having. Also, the description of the issue must clearly explain what is broken, not what you want us to implement. Go through this checklist and make sure you answer "YES" to all points:

  - You have all pre-requisites listed in README.md installed
  - You are sure that you are not reporting a duplicate (search all issues)
  - You say "is broken" or "doesn't work" in the title
  - You tell us what you are trying to do
  - You explain the results you are getting
  - You suggest an alternative result you would like to see

This article will help you understand what we are looking for: http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

Thank you for your contribution!

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@huweining[/z](https://www.0crat.com/u/huweining) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C9V6HBZQS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by HuWeining** [comment]
I use jcabi SSH client with the code below on a timed task.

int status =
                    new Shell.Verbose(new SSHByPassword(ip, shell.getPort(), shell.getAccount(), shell.getPassword()))
                        .exec(cmd, null, stdout, stderr);

The call frequency is about 5/s, after long time, the JVM keeps gc and the object DeleteOnExitHook hold the most of memory. under the /tmp, there are huge amount of files like jcabi-ssh1554258520000.key created by jcabi.

So what can i do to fix the problem. 
Thanks.

p.s. here is my maven dependency
 <dependency>
            <groupId>com.jcabi</groupId>
            <artifactId>jcabi-ssh</artifactId>
            <version>1.5</version>
 </dependency>

**Comment by yegor256** [comment]
@HuWeining this is definitely a bug in the library, let me try to fix it quickly.

**Comment by yegor256** [comment]
@HuWeining maybe you can submit a pull request? All we have to do is to delete the temp file after use, not only on exit.

**Comment by yegor256** [comment]
@HuWeining should be fine now
