### ISSUE TITLE
How to get it working on Java 11?

### ISSUE THREAD

**Issue by danuvian** [jcabi/jcabi-ssh#86]
Hello.

I went to https://www.yegor256.com/2014/09/02/java-ssh-client.html#disqus_thread and tried out the code samples and it works great. I was testing it using Java 8.

However, when I tried to use it in my real project, which is using Java 11, "jdk.nashorn.tools.Shell" is not accessible. I googled it and it appears that Nashorn has been deprecated in Java 11.

I really need to get this to work with Java 11. The "Shell" object is not available on this version.

Thanks for your help!

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@danuvian[/z](https://www.0crat.com/u/danuvian) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C9V6HBZQS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@danuvian good point. Do you have an idea of how to fix this? I don't... as of yet.

**Comment by AleksandrSokolov** [comment]
@danuvian 
It works fine for me in Java 11.
Please give more explanation about your problem.

**Comment by yegor256** [comment]
@danuvian works fine for me too
