### ISSUE TITLE
com.jcraft.jsch.JSchException: socket is not established

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-ssh#96]
sometimes this happens

**Comment by yegor256** [comment]
@rultor release, tag is `1.8.2`

**Comment by yegor256** [comment]
@rultor release, tag is `1.8.2`

**Comment by yegor256** [comment]
@rultor release, tag is `1.8.2`

**Comment by yegor256** [comment]
@rultor release, tag is `1.8.2`

**Comment by yegor256** [comment]
@rultor release, tag is `1.8.2`

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-ssh#96` is not assigned, can't get performer
